### ISSUE TITLE
Do we need jQuery?

### ISSUE THREAD

**Issue by KMikeeU** [IppSec/ippsec.github.io#11]
Loading jQuery takes up to about 100ms on my internet. Judging the rather minimal use of its functionality I wonder if it is really required for this project.

[This page](http://youmightnotneedjquery.com/) shows a couple of vanilla JS alternatives to the jQuery functions we use.

**Comment by IppSec** [comment]
The original implementation did not utilize JQuery, but also did a lot of other things horribly.  When the code was cleaned up, it switched to JQuery for speed of development.  

I wouldn't be opposed to removing that as a dependency.  I'll probably take a stab at it in a few weeks if you don't beat me to it.

**Comment by HexF** [comment]
A complete rewrite of the code would be required for jQuery to be dropped, although we could rebuild jQuery with only the features we need.

**Comment by IppSec** [comment]
Closing issue with @frnkst's commit.
