### ISSUE TITLE
Duplicate data - Blocky

### ISSUE THREAD

**Issue by Reelix** [IppSec/ippsec.github.io#13]
Search

> https://raw.githubusercontent.com/IppSec/ippsec.github.io/master/dataset.json

for

> "HackTheBox - Blocky", "videoId": "C2O-rilXA6I", "timestamp": {"minutes": 15, "seconds": 30}, "line": " Rabbit hole, gaining access through FTP"}

There should only be 1 result.

**Comment by IppSec** [comment]
Sorry for the late response, missed responding to this request.  Think I fixed it by editing my YouTube description, I am no longer seeing it twice.
