### ISSUE TITLE
Glitches in the Search algorithm

### ISSUE THREAD

**Issue by slinoracam** [IppSec/ippsec.github.io#16]
Hello, please find below two little glitches in the search algorithm I recently found. 

* _How to reproduce the first issue?_ In the search bar, if you type the word ```craft``` then 25 results from the HackTheBox - Craft video should appear. Now please only type the letter ```q``` then erase it with the backspace key. When you type the word ```craft``` again then... no result is found!

* _How to fix the first issue?_ I added in ```logic.js``` the line ```currentSet = window.dataset;``` located in the if/else statement of the doSearch function. When the variable ```val``` is an empty string, if the results are reset, the issue seems to be fixed. I also added the line ```noResults.style.display = 'none';``` in order to remove the "try being more specific" message when the search bar becomes empty.

```javascript
function doSearch(event) {
        -------------------------------------------cut----
       if (val != '') {
        -------------------------------------------cut----
        } else {
            controls.hideResults();
            window.controls.setColor(colorUpdate, 'no-search');
            noResults.style.display = 'none';
            currentSet = window.dataset;
        }
        -------------------------------------------cut----
    }
```

* _How to reproduce the second issue?_ In the search bar, if you type the word ```terminal``` then 7 results should appear to this day. Now please only erase the letter ```m``` with the backspace key: ```terinal``` returns zero results, which is fine. However, if you type again the letter ```m``` and then search for ```terminal``` again... no result will be found!

* _How to fix the second issue?_ I removed in ```logic.js``` the ```if (val.length < oldSearchValue.length)``` statement also located in the doSearch function. If you try to reproduce this issue by adding or removing letters in your search terms, it should return results.

```javascript
function doSearch(event) {
    -------------------------------------------cut----
    if (val != '') {
        controls.displayResults();
        currentSet = window.dataset;
        oldSearchValue = val;

        ---------------------------------------cut----
    } else {
        ---------------------------------------cut----
    }
```

**Comment by ippsec-htb** [comment]
Thanks for the report.  Should be fixed, let me know if it isn't.
