### ISSUE TITLE
irrelevant results if arbitary words are place

### ISSUE THREAD

**Issue by AlienX2001** [IppSec/ippsec.github.io#20]
Issue:-
If we put arbitary words from your transcript like "password" or "getting" or common words like that, then the site, or any app which integrate the json file will show lots of results

![image](https://user-images.githubusercontent.com/64488123/99527827-70a2a180-29c3-11eb-90d3-0899d85f517e.png)
and 
![image](https://user-images.githubusercontent.com/64488123/99527945-95971480-29c3-11eb-970a-07a40c214d47.png)

Fix:- 
Put only some specific words to search for like tool names, methodologies, box names, etc. instead of the whole transcript

**Comment by ecki** [comment]
I also did not find a way to search for “Java” but not “Javascript” (tried “java “ and “Java -javascript" and "java"

**Comment by IppSec** [comment]
@ecki I added the negative search option so now java -script will work.  It was added in 653776750bce4564222bef5bf0240c27815d46e7

As for the original issue with words like "password" causing too many results. I have no way to fix that, the search works based upon descriptions in my YT.  I'm not manually building an index for this site. Discord bot is community ran.

**Comment by ecki** [comment]
Thanks, works great.
