### ISSUE TITLE
API Keys

### ISSUE THREAD

**Issue by HexF** [IppSec/ippsec.github.io#6]
Twitter API keys are displayed on [this](https://ippsec.rocks/holidayhack2016/part-1/) page
They are not active, but its good practice to not put API keys on the net

**Comment by IppSec** [comment]
Good point - Had created a separate twitter account for the write and deleted it afterwards.  Still not a best practice to be showing it, I'll remove it later in the week.

**Comment by IppSec** [comment]
Removed the keys.
