### ISSUE TITLE
Direct link to mobile not working

### ISSUE THREAD

**Issue by IppSec** [IppSec/ippsec.github.io#9]
It appears the YouTube mobile site doesn’t obey the start get parameter.  I’ve only confirmed the bug have not looked into it.

Ex URL:
https://m.youtube.com/watch?start=540&v=krC5j1Ab44I

**Comment by fabiossilva21** [comment]
Use:

https://m.youtube.com/watch?t=540&v=krC5j1Ab44I


With parameter "t" not "start"

**Comment by IppSec** [comment]
Thanks @fabiossilva21 and @KMikeeU verified fixed and now closing.
